sudo: false
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - ./node_modules/.bin/bower install
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run build
  - yarn test
  - yarn run cover
  - yarn run codecov
after_script:
  - greenkeeper-lockfile-upload
