sudo: false
language: node_js
node_js:
  - "6.5.0"
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm install
  - ./node_modules/.bin/bower install

script:
  - npm run lint
  - npm run build
