sudo: false
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
install:
  - yarn install
  - ./node_modules/.bin/bower install
script:
  - yarn run lint
  - yarn run build
  - yarn test
  - yarn run cover
  - yarn run codecov
