sudo: false
language: node_js
node_js:
  - "8"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn build
  - yarn test
  - yarn run codecov
after_script:
  - greenkeeper-lockfile-upload
